//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.7.3081.0.
// 
namespace TestConsole.Integration.Ares.Schema {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_answer_basic/v_1.0.3")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_answer_basic/v_1.0.3", IsNullable=false)]
    public partial class Ares_odpovedi {
        
        private odpoved_basic[] odpovedField;
        
        private chybova_odpoved faultField;
        
        private System.DateTime odpoved_datum_casField;
        
        private int odpoved_pocetField;
        
        private ares_dotaz_typ odpoved_typField;
        
        private bool odpoved_typFieldSpecified;
        
        private vystup_format vystup_formatField;
        
        private xslt_ks xsltField;
        
        private string validation_XSLTField;
        
        private string idField;
        
        public Ares_odpovedi() {
            this.odpoved_typField = ares_dotaz_typ.Basic;
            this.vystup_formatField = vystup_format.XML;
            this.xsltField = xslt_ks.klient;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Odpoved")]
        public odpoved_basic[] Odpoved {
            get {
                return this.odpovedField;
            }
            set {
                this.odpovedField = value;
            }
        }
        
        /// <remarks/>
        public chybova_odpoved Fault {
            get {
                return this.faultField;
            }
            set {
                this.faultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime odpoved_datum_cas {
            get {
                return this.odpoved_datum_casField;
            }
            set {
                this.odpoved_datum_casField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int odpoved_pocet {
            get {
                return this.odpoved_pocetField;
            }
            set {
                this.odpoved_pocetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ares_dotaz_typ odpoved_typ {
            get {
                return this.odpoved_typField;
            }
            set {
                this.odpoved_typField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool odpoved_typSpecified {
            get {
                return this.odpoved_typFieldSpecified;
            }
            set {
                this.odpoved_typFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(vystup_format.XML)]
        public vystup_format vystup_format {
            get {
                return this.vystup_formatField;
            }
            set {
                this.vystup_formatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(xslt_ks.klient)]
        public xslt_ks xslt {
            get {
                return this.xsltField;
            }
            set {
                this.xsltField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string validation_XSLT {
            get {
                return this.validation_XSLTField;
            }
            set {
                this.validation_XSLTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3")]
    public partial class odpoved_basic {
        
        private int pIDField;
        
        private error_ARES eField;
        
        private vysledek_hledani vhField;
        
        private int pZAField;
        
        private uvod uVODField;
        
        private vypis_basic[] vBASField;
        
        /// <remarks/>
        public int PID {
            get {
                return this.pIDField;
            }
            set {
                this.pIDField = value;
            }
        }
        
        /// <remarks/>
        public error_ARES E {
            get {
                return this.eField;
            }
            set {
                this.eField = value;
            }
        }
        
        /// <remarks/>
        public vysledek_hledani VH {
            get {
                return this.vhField;
            }
            set {
                this.vhField = value;
            }
        }
        
        /// <remarks/>
        public int PZA {
            get {
                return this.pZAField;
            }
            set {
                this.pZAField = value;
            }
        }
        
        /// <remarks/>
        public uvod UVOD {
            get {
                return this.uVODField;
            }
            set {
                this.uVODField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VBAS")]
        public vypis_basic[] VBAS {
            get {
                return this.vBASField;
            }
            set {
                this.vBASField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3")]
    public partial class error_ARES {
        
        private sbyte ekField;
        
        private string etField;
        
        /// <remarks/>
        public sbyte EK {
            get {
                return this.ekField;
            }
            set {
                this.ekField = value;
            }
        }
        
        /// <remarks/>
        public string ET {
            get {
                return this.etField;
            }
            set {
                this.etField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3")]
    public partial class chybova_odpoved {
        
        private string faultcodeField;
        
        private string faultstringField;
        
        /// <remarks/>
        public string faultcode {
            get {
                return this.faultcodeField;
            }
            set {
                this.faultcodeField = value;
            }
        }
        
        /// <remarks/>
        public string faultstring {
            get {
                return this.faultstringField;
            }
            set {
                this.faultstringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3")]
    public partial class obor_cinnosti {
        
        private string kField;
        
        private string tField;
        
        private ano_ne aktivniField;
        
        private bool aktivniFieldSpecified;
        
        /// <remarks/>
        public string K {
            get {
                return this.kField;
            }
            set {
                this.kField = value;
            }
        }
        
        /// <remarks/>
        public string T {
            get {
                return this.tField;
            }
            set {
                this.tField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ano_ne aktivni {
            get {
                return this.aktivniField;
            }
            set {
                this.aktivniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool aktivniSpecified {
            get {
                return this.aktivniFieldSpecified;
            }
            set {
                this.aktivniFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3")]
    public enum ano_ne {
        
        /// <remarks/>
        A,
        
        /// <remarks/>
        N,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3")]
    public partial class texty {
        
        private textType[] tField;
        
        private System.DateTime dodField;
        
        private bool dodFieldSpecified;
        
        private System.DateTime ddoField;
        
        private bool ddoFieldSpecified;
        
        private zdroj_type zdrojField;
        
        private bool zdrojFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("T")]
        public textType[] T {
            get {
                return this.tField;
            }
            set {
                this.tField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime dod {
            get {
                return this.dodField;
            }
            set {
                this.dodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dodSpecified {
            get {
                return this.dodFieldSpecified;
            }
            set {
                this.dodFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime ddo {
            get {
                return this.ddoField;
            }
            set {
                this.ddoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ddoSpecified {
            get {
                return this.ddoFieldSpecified;
            }
            set {
                this.ddoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public zdroj_type zdroj {
            get {
                return this.zdrojField;
            }
            set {
                this.zdrojField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zdrojSpecified {
            get {
                return this.zdrojFieldSpecified;
            }
            set {
                this.zdrojFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3")]
    public partial class textType {
        
        private System.DateTime dodField;
        
        private bool dodFieldSpecified;
        
        private System.DateTime ddoField;
        
        private bool ddoFieldSpecified;
        
        private zdroj_type zdrojField;
        
        private bool zdrojFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime dod {
            get {
                return this.dodField;
            }
            set {
                this.dodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dodSpecified {
            get {
                return this.dodFieldSpecified;
            }
            set {
                this.dodFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime ddo {
            get {
                return this.ddoField;
            }
            set {
                this.ddoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ddoSpecified {
            get {
                return this.ddoFieldSpecified;
            }
            set {
                this.ddoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public zdroj_type zdroj {
            get {
                return this.zdrojField;
            }
            set {
                this.zdrojField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zdrojSpecified {
            get {
                return this.zdrojFieldSpecified;
            }
            set {
                this.zdrojFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3")]
    public enum zdroj_type {
        
        /// <remarks/>
        ARES,
        
        /// <remarks/>
        OR,
        
        /// <remarks/>
        RES,
        
        /// <remarks/>
        RZP,
        
        /// <remarks/>
        RŽP,
        
        /// <remarks/>
        RZZ,
        
        /// <remarks/>
        DPH,
        
        /// <remarks/>
        SD,
        
        /// <remarks/>
        SCP,
        
        /// <remarks/>
        CEU,
        
        /// <remarks/>
        CEDR,
        
        /// <remarks/>
        RARIS,
        
        /// <remarks/>
        RCNS,
        
        /// <remarks/>
        PSH,
        
        /// <remarks/>
        OSS,
        
        /// <remarks/>
        SZR,
        
        /// <remarks/>
        IR,
        
        /// <remarks/>
        SKO,
        
        /// <remarks/>
        EZP,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3")]
    public partial class kod_nace {
        
        private System.DateTime dodField;
        
        private bool dodFieldSpecified;
        
        private System.DateTime ddoField;
        
        private bool ddoFieldSpecified;
        
        private zdroj_type zdrojField;
        
        private bool zdrojFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime dod {
            get {
                return this.dodField;
            }
            set {
                this.dodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dodSpecified {
            get {
                return this.dodFieldSpecified;
            }
            set {
                this.dodFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime ddo {
            get {
                return this.ddoField;
            }
            set {
                this.ddoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ddoSpecified {
            get {
                return this.ddoFieldSpecified;
            }
            set {
                this.ddoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public zdroj_type zdroj {
            get {
                return this.zdrojField;
            }
            set {
                this.zdrojField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zdrojSpecified {
            get {
                return this.zdrojFieldSpecified;
            }
            set {
                this.zdrojFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3")]
    public partial class nace {
        
        private kod_nace[] nACEField;
        
        private string nazev_NACEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NACE")]
        public kod_nace[] NACE {
            get {
                return this.nACEField;
            }
            set {
                this.nACEField = value;
            }
        }
        
        /// <remarks/>
        public string Nazev_NACE {
            get {
                return this.nazev_NACEField;
            }
            set {
                this.nazev_NACEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3")]
    public partial class kod_okec {
        
        private System.DateTime dodField;
        
        private bool dodFieldSpecified;
        
        private System.DateTime ddoField;
        
        private bool ddoFieldSpecified;
        
        private zdroj_type zdrojField;
        
        private bool zdrojFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime dod {
            get {
                return this.dodField;
            }
            set {
                this.dodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dodSpecified {
            get {
                return this.dodFieldSpecified;
            }
            set {
                this.dodFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime ddo {
            get {
                return this.ddoField;
            }
            set {
                this.ddoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ddoSpecified {
            get {
                return this.ddoFieldSpecified;
            }
            set {
                this.ddoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public zdroj_type zdroj {
            get {
                return this.zdrojField;
            }
            set {
                this.zdrojField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zdrojSpecified {
            get {
                return this.zdrojFieldSpecified;
            }
            set {
                this.zdrojFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3")]
    public partial class okec {
        
        private kod_okec[] oKECField;
        
        private string noField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OKEC")]
        public kod_okec[] OKEC {
            get {
                return this.oKECField;
            }
            set {
                this.oKECField = value;
            }
        }
        
        /// <remarks/>
        public string NO {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3")]
    public partial class kategorie_poctu_pracovniku {
        
        private zdroj_type zdrojField;
        
        private bool zdrojFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public zdroj_type zdroj {
            get {
                return this.zdrojField;
            }
            set {
                this.zdrojField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zdrojSpecified {
            get {
                return this.zdrojFieldSpecified;
            }
            set {
                this.zdrojFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3")]
    public partial class stav_subjektu_ceu {
        
        private stav_upadce_CEU sKOField;
        
        private stav_upadce_CEU sVYField;
        
        /// <remarks/>
        public stav_upadce_CEU SKO {
            get {
                return this.sKOField;
            }
            set {
                this.sKOField = value;
            }
        }
        
        /// <remarks/>
        public stav_upadce_CEU SVY {
            get {
                return this.sVYField;
            }
            set {
                this.sVYField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3")]
    public enum stav_upadce_CEU {
        
        /// <remarks/>
        A,
        
        /// <remarks/>
        Z,
        
        /// <remarks/>
        N,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3")]
    public partial class financni_urad {
        
        private short kFUField;
        
        private string nFUField;
        
        /// <remarks/>
        public short KFU {
            get {
                return this.kFUField;
            }
            set {
                this.kFUField = value;
            }
        }
        
        /// <remarks/>
        public string NFU {
            get {
                return this.nFUField;
            }
            set {
                this.nFUField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3")]
    public partial class zivnostensky_urad {
        
        private int kZUField;
        
        private string nZUField;
        
        private string nField;
        
        private string nuField;
        
        private string pSCField;
        
        /// <remarks/>
        public int KZU {
            get {
                return this.kZUField;
            }
            set {
                this.kZUField = value;
            }
        }
        
        /// <remarks/>
        public string NZU {
            get {
                return this.nZUField;
            }
            set {
                this.nZUField = value;
            }
        }
        
        /// <remarks/>
        public string N {
            get {
                return this.nField;
            }
            set {
                this.nField = value;
            }
        }
        
        /// <remarks/>
        public string NU {
            get {
                return this.nuField;
            }
            set {
                this.nuField = value;
            }
        }
        
        /// <remarks/>
        public string PSC {
            get {
                return this.pSCField;
            }
            set {
                this.pSCField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3")]
    public partial class registrace_RZP {
        
        private zivnostensky_urad zuField;
        
        private ano_ne vjField;
        
        private bool vjFieldSpecified;
        
        private ano_ne orField;
        
        private bool orFieldSpecified;
        
        private financni_urad fuField;
        
        private ano_ne aktivniField;
        
        private bool aktivniFieldSpecified;
        
        /// <remarks/>
        public zivnostensky_urad ZU {
            get {
                return this.zuField;
            }
            set {
                this.zuField = value;
            }
        }
        
        /// <remarks/>
        public ano_ne VJ {
            get {
                return this.vjField;
            }
            set {
                this.vjField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VJSpecified {
            get {
                return this.vjFieldSpecified;
            }
            set {
                this.vjFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public ano_ne OR {
            get {
                return this.orField;
            }
            set {
                this.orField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ORSpecified {
            get {
                return this.orFieldSpecified;
            }
            set {
                this.orFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public financni_urad FU {
            get {
                return this.fuField;
            }
            set {
                this.fuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ano_ne aktivni {
            get {
                return this.aktivniField;
            }
            set {
                this.aktivniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool aktivniSpecified {
            get {
                return this.aktivniFieldSpecified;
            }
            set {
                this.aktivniFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3")]
    public partial class stav_KVZ {
        
        private int kField;
        
        private string tField;
        
        /// <remarks/>
        public int K {
            get {
                return this.kField;
            }
            set {
                this.kField = value;
            }
        }
        
        /// <remarks/>
        public string T {
            get {
                return this.tField;
            }
            set {
                this.tField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3")]
    public partial class stav {
        
        private stav_subjektu sSUField;
        
        private bool sSUFieldSpecified;
        
        private stav_KVZ kKZField;
        
        private stav_KVZ vyField;
        
        private stav_KVZ zAMField;
        
        private stav_KVZ liField;
        
        /// <remarks/>
        public stav_subjektu SSU {
            get {
                return this.sSUField;
            }
            set {
                this.sSUField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SSUSpecified {
            get {
                return this.sSUFieldSpecified;
            }
            set {
                this.sSUFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public stav_KVZ KKZ {
            get {
                return this.kKZField;
            }
            set {
                this.kKZField = value;
            }
        }
        
        /// <remarks/>
        public stav_KVZ VY {
            get {
                return this.vyField;
            }
            set {
                this.vyField = value;
            }
        }
        
        /// <remarks/>
        public stav_KVZ ZAM {
            get {
                return this.zAMField;
            }
            set {
                this.zAMField = value;
            }
        }
        
        /// <remarks/>
        public stav_KVZ LI {
            get {
                return this.liField;
            }
            set {
                this.liField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3")]
    public enum stav_subjektu {
        
        /// <remarks/>
        Aktivní,
        
        /// <remarks/>
        Zaniklý,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3")]
    public partial class soud {
        
        private int kField;
        
        private string tField;
        
        /// <remarks/>
        public int K {
            get {
                return this.kField;
            }
            set {
                this.kField = value;
            }
        }
        
        /// <remarks/>
        public string T {
            get {
                return this.tField;
            }
            set {
                this.tField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3")]
    public partial class spisova_znacka {
        
        private soud sdField;
        
        private string ovField;
        
        private System.DateTime dodField;
        
        private bool dodFieldSpecified;
        
        private System.DateTime ddoField;
        
        private bool ddoFieldSpecified;
        
        private zdroj_type zdrojField;
        
        private bool zdrojFieldSpecified;
        
        /// <remarks/>
        public soud SD {
            get {
                return this.sdField;
            }
            set {
                this.sdField = value;
            }
        }
        
        /// <remarks/>
        public string OV {
            get {
                return this.ovField;
            }
            set {
                this.ovField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime dod {
            get {
                return this.dodField;
            }
            set {
                this.dodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dodSpecified {
            get {
                return this.dodFieldSpecified;
            }
            set {
                this.dodFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime ddo {
            get {
                return this.ddoField;
            }
            set {
                this.ddoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ddoSpecified {
            get {
                return this.ddoFieldSpecified;
            }
            set {
                this.ddoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public zdroj_type zdroj {
            get {
                return this.zdrojField;
            }
            set {
                this.zdrojField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zdrojSpecified {
            get {
                return this.zdrojFieldSpecified;
            }
            set {
                this.zdrojFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3")]
    public partial class registrace {
        
        private spisova_znacka[] szField;
        
        private stav sORField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SZ")]
        public spisova_znacka[] SZ {
            get {
                return this.szField;
            }
            set {
                this.szField = value;
            }
        }
        
        /// <remarks/>
        public stav SOR {
            get {
                return this.sORField;
            }
            set {
                this.sORField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.3")]
    public partial class adresa_UIR {
        
        private string kOLField;
        
        private string kkField;
        
        private string kOKField;
        
        private string koField;
        
        private string kPOField;
        
        private string kSOField;
        
        private string knField;
        
        private string kCOField;
        
        private string kMCField;
        
        private string pSCField;
        
        private string kULField;
        
        private int cdField;
        
        private bool cdFieldSpecified;
        
        private sbyte tCDField;
        
        private bool tCDFieldSpecified;
        
        private string coField;
        
        private string pCOField;
        
        private string kaField;
        
        private string kOBField;
        
        private string pCDField;
        
        /// <remarks/>
        public string KOL {
            get {
                return this.kOLField;
            }
            set {
                this.kOLField = value;
            }
        }
        
        /// <remarks/>
        public string KK {
            get {
                return this.kkField;
            }
            set {
                this.kkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string KOK {
            get {
                return this.kOKField;
            }
            set {
                this.kOKField = value;
            }
        }
        
        /// <remarks/>
        public string KO {
            get {
                return this.koField;
            }
            set {
                this.koField = value;
            }
        }
        
        /// <remarks/>
        public string KPO {
            get {
                return this.kPOField;
            }
            set {
                this.kPOField = value;
            }
        }
        
        /// <remarks/>
        public string KSO {
            get {
                return this.kSOField;
            }
            set {
                this.kSOField = value;
            }
        }
        
        /// <remarks/>
        public string KN {
            get {
                return this.knField;
            }
            set {
                this.knField = value;
            }
        }
        
        /// <remarks/>
        public string KCO {
            get {
                return this.kCOField;
            }
            set {
                this.kCOField = value;
            }
        }
        
        /// <remarks/>
        public string KMC {
            get {
                return this.kMCField;
            }
            set {
                this.kMCField = value;
            }
        }
        
        /// <remarks/>
        public string PSC {
            get {
                return this.pSCField;
            }
            set {
                this.pSCField = value;
            }
        }
        
        /// <remarks/>
        public string KUL {
            get {
                return this.kULField;
            }
            set {
                this.kULField = value;
            }
        }
        
        /// <remarks/>
        public int CD {
            get {
                return this.cdField;
            }
            set {
                this.cdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CDSpecified {
            get {
                return this.cdFieldSpecified;
            }
            set {
                this.cdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public sbyte TCD {
            get {
                return this.tCDField;
            }
            set {
                this.tCDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TCDSpecified {
            get {
                return this.tCDFieldSpecified;
            }
            set {
                this.tCDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string CO {
            get {
                return this.coField;
            }
            set {
                this.coField = value;
            }
        }
        
        /// <remarks/>
        public string PCO {
            get {
                return this.pCOField;
            }
            set {
                this.pCOField = value;
            }
        }
        
        /// <remarks/>
        public string KA {
            get {
                return this.kaField;
            }
            set {
                this.kaField = value;
            }
        }
        
        /// <remarks/>
        public string KOB {
            get {
                return this.kOBField;
            }
            set {
                this.kOBField = value;
            }
        }
        
        /// <remarks/>
        public string PCD {
            get {
                return this.pCDField;
            }
            set {
                this.pCDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3")]
    public partial class adresa_ARES {
        
        private string iDAField;
        
        private string ksField;
        
        private string nsField;
        
        private string nOKField;
        
        private string nField;
        
        private string nCOField;
        
        private string nMCField;
        
        private string nuField;
        
        private int cdField;
        
        private bool cdFieldSpecified;
        
        private sbyte tCDField;
        
        private bool tCDFieldSpecified;
        
        private string coField;
        
        private string caField;
        
        private string pSCField;
        
        private string zahr_PSCField;
        
        private string atField;
        
        private adresa_UIR auField;
        
        private System.DateTime dodField;
        
        private bool dodFieldSpecified;
        
        private System.DateTime ddoField;
        
        private bool ddoFieldSpecified;
        
        private zdroj_type zdrojField;
        
        private bool zdrojFieldSpecified;
        
        /// <remarks/>
        public string IDA {
            get {
                return this.iDAField;
            }
            set {
                this.iDAField = value;
            }
        }
        
        /// <remarks/>
        public string KS {
            get {
                return this.ksField;
            }
            set {
                this.ksField = value;
            }
        }
        
        /// <remarks/>
        public string NS {
            get {
                return this.nsField;
            }
            set {
                this.nsField = value;
            }
        }
        
        /// <remarks/>
        public string NOK {
            get {
                return this.nOKField;
            }
            set {
                this.nOKField = value;
            }
        }
        
        /// <remarks/>
        public string N {
            get {
                return this.nField;
            }
            set {
                this.nField = value;
            }
        }
        
        /// <remarks/>
        public string NCO {
            get {
                return this.nCOField;
            }
            set {
                this.nCOField = value;
            }
        }
        
        /// <remarks/>
        public string NMC {
            get {
                return this.nMCField;
            }
            set {
                this.nMCField = value;
            }
        }
        
        /// <remarks/>
        public string NU {
            get {
                return this.nuField;
            }
            set {
                this.nuField = value;
            }
        }
        
        /// <remarks/>
        public int CD {
            get {
                return this.cdField;
            }
            set {
                this.cdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CDSpecified {
            get {
                return this.cdFieldSpecified;
            }
            set {
                this.cdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public sbyte TCD {
            get {
                return this.tCDField;
            }
            set {
                this.tCDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TCDSpecified {
            get {
                return this.tCDFieldSpecified;
            }
            set {
                this.tCDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string CO {
            get {
                return this.coField;
            }
            set {
                this.coField = value;
            }
        }
        
        /// <remarks/>
        public string CA {
            get {
                return this.caField;
            }
            set {
                this.caField = value;
            }
        }
        
        /// <remarks/>
        public string PSC {
            get {
                return this.pSCField;
            }
            set {
                this.pSCField = value;
            }
        }
        
        /// <remarks/>
        public string Zahr_PSC {
            get {
                return this.zahr_PSCField;
            }
            set {
                this.zahr_PSCField = value;
            }
        }
        
        /// <remarks/>
        public string AT {
            get {
                return this.atField;
            }
            set {
                this.atField = value;
            }
        }
        
        /// <remarks/>
        public adresa_UIR AU {
            get {
                return this.auField;
            }
            set {
                this.auField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime dod {
            get {
                return this.dodField;
            }
            set {
                this.dodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dodSpecified {
            get {
                return this.dodFieldSpecified;
            }
            set {
                this.dodFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime ddo {
            get {
                return this.ddoField;
            }
            set {
                this.ddoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ddoSpecified {
            get {
                return this.ddoFieldSpecified;
            }
            set {
                this.ddoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public zdroj_type zdroj {
            get {
                return this.zdrojField;
            }
            set {
                this.zdrojField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zdrojSpecified {
            get {
                return this.zdrojFieldSpecified;
            }
            set {
                this.zdrojFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3")]
    public partial class adresa_dorucovaci {
        
        private string ucField;
        
        private string pbField;
        
        private zdroj_type zdrojField;
        
        private bool zdrojFieldSpecified;
        
        /// <remarks/>
        public string UC {
            get {
                return this.ucField;
            }
            set {
                this.ucField = value;
            }
        }
        
        /// <remarks/>
        public string PB {
            get {
                return this.pbField;
            }
            set {
                this.pbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public zdroj_type zdroj {
            get {
                return this.zdrojField;
            }
            set {
                this.zdrojField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zdrojSpecified {
            get {
                return this.zdrojFieldSpecified;
            }
            set {
                this.zdrojFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3")]
    public partial class pravni_forma {
        
        private short kPFField;
        
        private bool kPFFieldSpecified;
        
        private string nPFField;
        
        private pf_osoba pFOField;
        
        private bool pFOFieldSpecified;
        
        private textType[] tField;
        
        private tzu_osoba tZUField;
        
        private bool tZUFieldSpecified;
        
        private System.DateTime dodField;
        
        private bool dodFieldSpecified;
        
        private System.DateTime ddoField;
        
        private bool ddoFieldSpecified;
        
        private zdroj_type zdrojField;
        
        private bool zdrojFieldSpecified;
        
        /// <remarks/>
        public short KPF {
            get {
                return this.kPFField;
            }
            set {
                this.kPFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KPFSpecified {
            get {
                return this.kPFFieldSpecified;
            }
            set {
                this.kPFFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string NPF {
            get {
                return this.nPFField;
            }
            set {
                this.nPFField = value;
            }
        }
        
        /// <remarks/>
        public pf_osoba PFO {
            get {
                return this.pFOField;
            }
            set {
                this.pFOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PFOSpecified {
            get {
                return this.pFOFieldSpecified;
            }
            set {
                this.pFOFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("T")]
        public textType[] T {
            get {
                return this.tField;
            }
            set {
                this.tField = value;
            }
        }
        
        /// <remarks/>
        public tzu_osoba TZU {
            get {
                return this.tZUField;
            }
            set {
                this.tZUField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TZUSpecified {
            get {
                return this.tZUFieldSpecified;
            }
            set {
                this.tZUFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime dod {
            get {
                return this.dodField;
            }
            set {
                this.dodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dodSpecified {
            get {
                return this.dodFieldSpecified;
            }
            set {
                this.dodFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime ddo {
            get {
                return this.ddoField;
            }
            set {
                this.ddoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ddoSpecified {
            get {
                return this.ddoFieldSpecified;
            }
            set {
                this.ddoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public zdroj_type zdroj {
            get {
                return this.zdrojField;
            }
            set {
                this.zdrojField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zdrojSpecified {
            get {
                return this.zdrojFieldSpecified;
            }
            set {
                this.zdrojFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3")]
    public enum pf_osoba {
        
        /// <remarks/>
        P,
        
        /// <remarks/>
        F,
        
        /// <remarks/>
        Z,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3")]
    public enum tzu_osoba {
        
        /// <remarks/>
        T,
        
        /// <remarks/>
        Z,
        
        /// <remarks/>
        U,
        
        /// <remarks/>
        E,
        
        /// <remarks/>
        Tuzemská,
        
        /// <remarks/>
        Zahraniční,
        
        /// <remarks/>
        Uprchlík,
        
        /// <remarks/>
        Evropská,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3")]
    public partial class obchodni_firma {
        
        private System.DateTime dodField;
        
        private bool dodFieldSpecified;
        
        private System.DateTime ddoField;
        
        private bool ddoFieldSpecified;
        
        private zdroj_type zdrojField;
        
        private bool zdrojFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime dod {
            get {
                return this.dodField;
            }
            set {
                this.dodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dodSpecified {
            get {
                return this.dodFieldSpecified;
            }
            set {
                this.dodFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime ddo {
            get {
                return this.ddoField;
            }
            set {
                this.ddoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ddoSpecified {
            get {
                return this.ddoFieldSpecified;
            }
            set {
                this.ddoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public zdroj_type zdroj {
            get {
                return this.zdrojField;
            }
            set {
                this.zdrojField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zdrojSpecified {
            get {
                return this.zdrojFieldSpecified;
            }
            set {
                this.zdrojFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3")]
    public partial class dic {
        
        private zdroj_type zdrojField;
        
        private bool zdrojFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public zdroj_type zdroj {
            get {
                return this.zdrojField;
            }
            set {
                this.zdrojField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zdrojSpecified {
            get {
                return this.zdrojFieldSpecified;
            }
            set {
                this.zdrojFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3")]
    public partial class ico {
        
        private System.DateTime dodField;
        
        private bool dodFieldSpecified;
        
        private System.DateTime ddoField;
        
        private bool ddoFieldSpecified;
        
        private zdroj_type zdrojField;
        
        private bool zdrojFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime dod {
            get {
                return this.dodField;
            }
            set {
                this.dodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dodSpecified {
            get {
                return this.dodFieldSpecified;
            }
            set {
                this.dodFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime ddo {
            get {
                return this.ddoField;
            }
            set {
                this.ddoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ddoSpecified {
            get {
                return this.ddoFieldSpecified;
            }
            set {
                this.ddoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public zdroj_type zdroj {
            get {
                return this.zdrojField;
            }
            set {
                this.zdrojField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zdrojSpecified {
            get {
                return this.zdrojFieldSpecified;
            }
            set {
                this.zdrojFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3")]
    public partial class vypis_basic {
        
        private ico iCOField;
        
        private dic dICField;
        
        private obchodni_firma ofField;
        
        private System.DateTime dvField;
        
        private bool dvFieldSpecified;
        
        private System.DateTime dzField;
        
        private bool dzFieldSpecified;
        
        private pravni_forma pfField;
        
        private pravni_forma[] doplnujici_PFField;
        
        private adresa_dorucovaci adField;
        
        private adresa_ARES aaField;
        
        private adresa_ARES adr_puvField;
        
        private string pSUField;
        
        private registrace[] rORField;
        
        private registrace_RZP[] rRZField;
        
        private stav_subjektu_ceu sCEUField;
        
        private kategorie_poctu_pracovniku kPPField;
        
        private okec[] oKECEField;
        
        private nace[] naceField;
        
        private texty[] pPIField;
        
        private obor_cinnosti[] obory_cinnostiField;
        
        /// <remarks/>
        public ico ICO {
            get {
                return this.iCOField;
            }
            set {
                this.iCOField = value;
            }
        }
        
        /// <remarks/>
        public dic DIC {
            get {
                return this.dICField;
            }
            set {
                this.dICField = value;
            }
        }
        
        /// <remarks/>
        public obchodni_firma OF {
            get {
                return this.ofField;
            }
            set {
                this.ofField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DV {
            get {
                return this.dvField;
            }
            set {
                this.dvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DVSpecified {
            get {
                return this.dvFieldSpecified;
            }
            set {
                this.dvFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DZ {
            get {
                return this.dzField;
            }
            set {
                this.dzField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DZSpecified {
            get {
                return this.dzFieldSpecified;
            }
            set {
                this.dzFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public pravni_forma PF {
            get {
                return this.pfField;
            }
            set {
                this.pfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("PF", IsNullable=false)]
        public pravni_forma[] Doplnujici_PF {
            get {
                return this.doplnujici_PFField;
            }
            set {
                this.doplnujici_PFField = value;
            }
        }
        
        /// <remarks/>
        public adresa_dorucovaci AD {
            get {
                return this.adField;
            }
            set {
                this.adField = value;
            }
        }
        
        /// <remarks/>
        public adresa_ARES AA {
            get {
                return this.aaField;
            }
            set {
                this.aaField = value;
            }
        }
        
        /// <remarks/>
        public adresa_ARES Adr_puv {
            get {
                return this.adr_puvField;
            }
            set {
                this.adr_puvField = value;
            }
        }
        
        /// <remarks/>
        public string PSU {
            get {
                return this.pSUField;
            }
            set {
                this.pSUField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ROR")]
        public registrace[] ROR {
            get {
                return this.rORField;
            }
            set {
                this.rORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RRZ")]
        public registrace_RZP[] RRZ {
            get {
                return this.rRZField;
            }
            set {
                this.rRZField = value;
            }
        }
        
        /// <remarks/>
        public stav_subjektu_ceu SCEU {
            get {
                return this.sCEUField;
            }
            set {
                this.sCEUField = value;
            }
        }
        
        /// <remarks/>
        public kategorie_poctu_pracovniku KPP {
            get {
                return this.kPPField;
            }
            set {
                this.kPPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OKECE")]
        public okec[] OKECE {
            get {
                return this.oKECEField;
            }
            set {
                this.oKECEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Nace")]
        public nace[] Nace {
            get {
                return this.naceField;
            }
            set {
                this.naceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("PP", IsNullable=false)]
        public texty[] PPI {
            get {
                return this.pPIField;
            }
            set {
                this.pPIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Obor_cinnosti", IsNullable=false)]
        public obor_cinnosti[] Obory_cinnosti {
            get {
                return this.obory_cinnostiField;
            }
            set {
                this.obory_cinnostiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3")]
    public partial class uvod {
        
        private string ndField;
        
        private System.DateTime aDBField;
        
        private bool aDBFieldSpecified;
        
        private System.DateTime dVYField;
        
        private bool dVYFieldSpecified;
        
        private System.DateTime cASField;
        
        private bool cASFieldSpecified;
        
        private string tvField;
        
        private System.DateTime pDPField;
        
        private bool pDPFieldSpecified;
        
        private string typ_odkazuField;
        
        private string typ_odpovediField;
        
        /// <remarks/>
        public string ND {
            get {
                return this.ndField;
            }
            set {
                this.ndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime ADB {
            get {
                return this.aDBField;
            }
            set {
                this.aDBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ADBSpecified {
            get {
                return this.aDBFieldSpecified;
            }
            set {
                this.aDBFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DVY {
            get {
                return this.dVYField;
            }
            set {
                this.dVYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DVYSpecified {
            get {
                return this.dVYFieldSpecified;
            }
            set {
                this.dVYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
        public System.DateTime CAS {
            get {
                return this.cASField;
            }
            set {
                this.cASField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CASSpecified {
            get {
                return this.cASFieldSpecified;
            }
            set {
                this.cASFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string TV {
            get {
                return this.tvField;
            }
            set {
                this.tvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime PDP {
            get {
                return this.pDPField;
            }
            set {
                this.pDPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PDPSpecified {
            get {
                return this.pDPFieldSpecified;
            }
            set {
                this.pDPFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Typ_odkazu {
            get {
                return this.typ_odkazuField;
            }
            set {
                this.typ_odkazuField = value;
            }
        }
        
        /// <remarks/>
        public string Typ_odpovedi {
            get {
                return this.typ_odpovediField;
            }
            set {
                this.typ_odpovediField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3")]
    public partial class vysledek_hledani {
        
        private int kField;
        
        private System.DateTime dvField;
        
        private bool dvFieldSpecified;
        
        private string tField;
        
        /// <remarks/>
        public int K {
            get {
                return this.kField;
            }
            set {
                this.kField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DV {
            get {
                return this.dvField;
            }
            set {
                this.dvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DVSpecified {
            get {
                return this.dvFieldSpecified;
            }
            set {
                this.dvFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string T {
            get {
                return this.tField;
            }
            set {
                this.tField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3")]
    public enum ares_dotaz_typ {
        
        /// <remarks/>
        Standard,
        
        /// <remarks/>
        Seznam_Reg,
        
        /// <remarks/>
        Vypis_OR,
        
        /// <remarks/>
        Vypis_RZP,
        
        /// <remarks/>
        Vypis_RES,
        
        /// <remarks/>
        Vypis_RZZ,
        
        /// <remarks/>
        Basic,
        
        /// <remarks/>
        Vypis_CNS,
        
        /// <remarks/>
        Vypis_OSS,
        
        /// <remarks/>
        Stdadr,
        
        /// <remarks/>
        zl,
        
        /// <remarks/>
        es,
        
        /// <remarks/>
        su,
        
        /// <remarks/>
        fo,
        
        /// <remarks/>
        ceu,
        
        /// <remarks/>
        zm,
        
        /// <remarks/>
        szr,
        
        /// <remarks/>
        Vypis_OFF,
        
        /// <remarks/>
        Vypis_PSH,
        
        /// <remarks/>
        Vypis_IR,
        
        /// <remarks/>
        Vypis_SKO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3")]
    public enum vystup_format {
        
        /// <remarks/>
        XML,
        
        /// <remarks/>
        HTML,
        
        /// <remarks/>
        XHTML,
        
        /// <remarks/>
        TEXT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3")]
    public enum xslt_ks {
        
        /// <remarks/>
        klient,
        
        /// <remarks/>
        server,
        
        /// <remarks/>
        savexml,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.3")]
    [System.Xml.Serialization.XmlRootAttribute("E_list", Namespace="http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.3", IsNullable=false)]
    public partial class xslt_error_list {
        
        private xslt_error_listE[] eField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("E")]
        public xslt_error_listE[] E {
            get {
                return this.eField;
            }
            set {
                this.eField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.3")]
    public partial class xslt_error_listE {
        
        private int record_IDField;
        
        private bool record_IDFieldSpecified;
        
        private error_type e_typeField;
        
        private error_kod e_IDField;
        
        private string etField;
        
        /// <remarks/>
        public int Record_ID {
            get {
                return this.record_IDField;
            }
            set {
                this.record_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Record_IDSpecified {
            get {
                return this.record_IDFieldSpecified;
            }
            set {
                this.record_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public error_type E_type {
            get {
                return this.e_typeField;
            }
            set {
                this.e_typeField = value;
            }
        }
        
        /// <remarks/>
        public error_kod E_ID {
            get {
                return this.e_IDField;
            }
            set {
                this.e_IDField = value;
            }
        }
        
        /// <remarks/>
        public string ET {
            get {
                return this.etField;
            }
            set {
                this.etField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.3")]
    public enum error_type {
        
        /// <remarks/>
        global,
        
        /// <remarks/>
        local,
        
        /// <remarks/>
        info,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.3")]
    public enum error_kod {
        
        /// <remarks/>
        versionMismatch,
        
        /// <remarks/>
        MustUnderstand,
        
        /// <remarks/>
        Client,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Client.RequestNamespace")]
        ClientRequestNamespace,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Client.SchemaNamespace")]
        ClientSchemaNamespace,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Client.Signature")]
        ClientSignature,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Client.Validity")]
        ClientValidity,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Client.WellFormedness")]
        ClientWellFormedness,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Client.XSLTNamespace")]
        ClientXSLTNamespace,
        
        /// <remarks/>
        Server,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Server.DatabaseConsistence")]
        ServerDatabaseConsistence,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Server.Program")]
        ServerProgram,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Server.Service")]
        ServerService,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Server.SQLStatement")]
        ServerSQLStatement,
    }
}
